spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:library
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      mode: embedded
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    contexts: ddl,dml

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library-app

  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

app:
  job-name: migrationJob
  chunk-size: 10
  cache-size-limit: 100
  h2-server-enabled: true